<?php
// ==============================================================================
// datos_album.php - Banco de Datos Oficial del Álbum Mundial 2026 (Expandido)
// ==============================================================================

return [
    // 🏆 ESPECIALES Y ESTADIOS PANINI
    ['FWC 0', 'Escudo Panini', 1, 0],
    ['FWC 1', 'Trofeo de la Copa del Mundo', 1, 0],
    ['FWC 2', 'Trofeo de la Copa del Mundo', 1, 0],
    ['FWC 3', 'Mascotas Maple Zayu Clutch', 1, 0],
    ['FWC 4', 'Logo de Copa del Mundo', 1, 0],
    ['FWC 5', 'Trionda Official Match Ball F2026', 1, 0],
    ['FWC 6', 'Estadios Canadá', 1, 0],
    ['FWC 7', 'Estadios México', 1, 0],
    ['FWC 8', 'Estadios USA', 1, 0],
    ['FWC 9', 'Fifa World Cup Italy 1934', 1, 0],
    ['FWC 10', 'Fifa World Cup Brazil 1950', 1, 0],
    ['FWC 11', 'Fifa World Cup Switzerland 1954', 1, 0],
    ['FWC 12', 'Fifa World Cup Chile 1962', 1, 0],
    ['FWC 13', 'Fifa World Cup Germany 1974', 1, 0],
    ['FWC 14', 'Fifa World Cup Mexico 1986', 1, 0],
    ['FWC 15', 'Fifa World Cup USA 1994', 1, 0],
    ['FWC 16', 'Fifa World Cup Korea/Japan 2002', 1, 0],
    ['FWC 17', 'Fifa World Cup Germany 2006', 1, 0],
    ['FWC 18', 'Fifa World Cup Brazil 2014', 1, 0],
    ['FWC 19', 'Fifa World Cup Qatar 2022', 1, 0],
    // 🇲🇽 MÉXICO
    ['MEX 1', 'Escudo México', 0, 0],
    ['MEX 2', 'Luis Malagón', 0, 0],
    ['MEX 3', 'Johan Vásquez', 0, 0],
    ['MEX 4', 'César Montes', 0, 0],
    ['MEX 5', 'Jorge Sánchez', 0, 0],
    ['MEX 6', 'Jesús Angulo', 0, 0],
    ['MEX 7', 'Israel Reyes', 0, 0],
    ['MEX 8', 'Luis Romo', 0, 0],
    ['MEX 9', 'Edson Álvarez', 0, 0],
    ['MEX 10', 'Orbelín Pineda', 0, 0],
    ['MEX 11', 'Luis Chávez', 0, 0],
    ['MEX 12', 'Santiago Giménez', 0, 0],
    ['MEX 13', 'Equipo México', 0, 0],
    ['MEX 14', 'Carlos Rodríguez', 0, 0],
    ['MEX 15', 'César Huerta', 0, 0],
    ['MEX 16', 'Alexis Vega', 0, 0],
    ['MEX 17', 'Roberto Alvarado', 0, 0],
    ['MEX 18', 'Henry Martín', 0, 0],
    ['MEX 19', 'Raúl Jiménez', 0, 0],
    ['MEX 20', 'Guillermo Ochoa', 0, 0],
    // 🇿🇦 SUDÁFRICA
    ['RSA 1', 'Escudo Sudáfrica', 0, 0],
    ['RSA 2', 'Ronwen Williams', 0, 0],
    ['RSA 3', 'Mothobi Mvala', 0, 0],
    ['RSA 4', 'Grant Kekana', 0, 0],
    ['RSA 5', 'Khuliso Mudau', 0, 0],
    ['RSA 6', 'Aubrey Modiba', 0, 0],
    ['RSA 7', 'Nkosinathi Sibisi', 0, 0],
    ['RSA 8', 'Teboho Mokoena', 0, 0],
    ['RSA 9', 'Sphephelo Sithole', 0, 0],
    ['RSA 10', 'Thapelo Morena', 0, 0],
    ['RSA 11', 'Themba Zwane', 0, 0],
    ['RSA 12', 'Patrick Maswanganyi', 0, 0],
    ['RSA 13', 'Equipo Sudáfrica', 0, 0],
    ['RSA 14', 'Percy Tau', 0, 0],
    ['RSA 15', 'Evidence Makgopa', 0, 0],
    ['RSA 16', 'Iqraam Rayners', 0, 0],
    ['RSA 17', 'Elias Mokwana', 0, 0],
    ['RSA 18', 'Nyiko Mobbie', 0, 0],
    ['RSA 19', 'Terrence Mashego', 0, 0],
    ['RSA 20', 'Veli Mothwa', 0, 0],
    // 🇰🇷 COREA DEL SUR
    ['KOR 1', 'Escudo Corea del Sur', 0, 0],
    ['KOR 2', 'Jo Hyeon-woo', 0, 0],
    ['KOR 3', 'Kim Min-jae', 0, 0],
    ['KOR 4', 'Kim Young-gwon', 0, 0],
    ['KOR 5', 'Kim Jin-su', 0, 0],
    ['KOR 6', 'Seol Young-woo', 0, 0],
    ['KOR 7', 'Hwang In-beom', 0, 0],
    ['KOR 8', 'Park Yong-woo', 0, 0],
    ['KOR 9', 'Lee Jae-sung', 0, 0],
    ['KOR 10', 'Hong Hyun-seok', 0, 0],
    ['KOR 11', 'Son Heung-min', 0, 0],
    ['KOR 12', 'Lee Kang-in', 0, 0],
    ['KOR 13', 'Equipo Corea del Sur', 0, 0],
    ['KOR 14', 'Hwang Hee-chan', 0, 0],
    ['KOR 15', 'Cho Gue-sung', 0, 0],
    ['KOR 16', 'Joo Min-kyu', 0, 0],
    ['KOR 17', 'Jeong Woo-yeong', 0, 0],
    ['KOR 18', 'Cho Yu-min', 0, 0],
    ['KOR 19', 'Kwon Kyung-won', 0, 0],
    ['KOR 20', 'Song Bum-keun', 0, 0],
    // 🇨🇿 CHEQUIA
    ['CZE 1', 'Escudo Chequia', 0, 0],
    ['CZE 2', 'Jindřich Staněk', 0, 0],
    ['CZE 3', 'Tomáš Holeš', 0, 0],
    ['CZE 4', 'Robin Hranáč', 0, 0],
    ['CZE 5', 'Ladislav Krejčí', 0, 0],
    ['CZE 6', 'Vladimír Coufal', 0, 0],
    ['CZE 7', 'David Douděra', 0, 0],
    ['CZE 8', 'Tomáš Souček', 0, 0],
    ['CZE 9', 'Lukáš Provod', 0, 0],
    ['CZE 10', 'Antonín Barák', 0, 0],
    ['CZE 11', 'Pavel Šulc', 0, 0],
    ['CZE 12', 'Patrik Schick', 0, 0],
    ['CZE 13', 'Equipo Chequia', 0, 0],
    ['CZE 14', 'Jan Kuchta', 0, 0],
    ['CZE 15', 'Adam Hložek', 0, 0],
    ['CZE 16', 'Mojmír Chytil', 0, 0],
    ['CZE 17', 'David Zima', 0, 0],
    ['CZE 18', 'Tomáš Chorý', 0, 0],
    ['CZE 19', 'Martin Vitík', 0, 0],
    ['CZE 20', 'Matěj Kovář', 0, 0],
    // 🇨🇦 CANADÁ
    ['CAN 1', 'Escudo Canadá', 0, 0],
    ['CAN 2', 'Dyne St. Clair', 0, 0],
    ['CAN 3', 'Alphonso Davies', 0, 0],
    ['CAN 4', 'Alistair Johnston', 0, 0],
    ['CAN 5', 'Samuel Adekugbe', 0, 0],
    ['CAN 6', 'Richie Larvea', 0, 0],
    ['CAN 7', 'Derek Cornelius', 0, 0],
    ['CAN 8', 'Moise Bombito', 0, 0],
    ['CAN 9', 'Kamal Miller', 0, 0],
    ['CAN 10', 'Stephen Eustáquio', 0, 0],
    ['CAN 11', 'Ismael koné', 0, 0],
    ['CAN 12', 'Jonathan Osorio', 0, 0],
    ['CAN 13', 'Equipo Canadá', 0, 0],
    ['CAN 14', 'Jacob Shaffelburg', 0, 0],
    ['CAN 15', 'Mathieu Choiniere', 0, 0],
    ['CAN 16', 'Niko Sigur', 0, 0],
    ['CAN 17', 'Tajon Buchanan', 0, 0],
    ['CAN 18', 'Liam Millar', 0, 0],
    ['CAN 19', 'Cyle Larin', 0, 0],
    ['CAN 20', 'Jonathan David', 0, 0],
    // 🇧🇦 BOSNIA Y HERZEGOVINA
    ['BIH 1', 'Escudo Bosnia y H.', 0, 0],
    ['BIH 2', 'Nikola Vasilj', 0, 0],
    ['BIH 3', 'Anel Ahmedhodžić', 0, 0],
    ['BIH 4', 'Dennis Hadžikadunić', 0, 0],
    ['BIH 5', 'Nikola Katić', 0, 0],
    ['BIH 6', 'Sead Kolašinac', 0, 0],
    ['BIH 7', 'Jusuf Gazibegović', 0, 0],
    ['BIH 8', 'Benjamin Tahirović', 0, 0],
    ['BIH 9', 'Rade Krunić', 0, 0],
    ['BIH 10', 'Denis Huseinbašić', 0, 0],
    ['BIH 11', 'Haris Hajradinović', 0, 0],
    ['BIH 12', 'Amar Dedić', 0, 0],
    ['BIH 13', 'Equipo Bosnia y H.', 0, 0],
    ['BIH 14', 'Ermedin Demirović', 0, 0],
    ['BIH 15', 'Edin Džeko', 0, 0],
    ['BIH 16', 'Haris Tabaković', 0, 0],
    ['BIH 17', 'Armin Gigović', 0, 0],
    ['BIH 18', 'Stjepan Radeljić', 0, 0],
    ['BIH 19', 'Dženis Burnić', 0, 0],
    ['BIH 20', 'Kenan Pirić', 0, 0],
    // 🇶🇦 QATAR
    ['QAT 1', 'Escudo Qatar', 0, 0],
    ['QAT 2', 'Meshaal Barsham', 0, 0],
    ['QAT 3', 'Lucas Mendes', 0, 0],
    ['QAT 4', 'Boualem Khoukhi', 0, 0],
    ['QAT 5', 'Al-Mahdi Ali Mukhtar', 0, 0],
    ['QAT 6', 'Pedro Miguel', 0, 0],
    ['QAT 7', 'Mohammed Waad', 0, 0],
    ['QAT 8', 'Jassem Gaber', 0, 0],
    ['QAT 9', 'Ahmed Fathy', 0, 0],
    ['QAT 10', 'Hassan Al-Haydos', 0, 0],
    ['QAT 11', 'Akram Afif', 0, 0],
    ['QAT 12', 'Almoez Ali', 0, 0],
    ['QAT 13', 'Equipo Qatar', 0, 0],
    ['QAT 14', 'Yusuf Abdurisag', 0, 0],
    ['QAT 15', 'Bassam Al-Rawi', 0, 0],
    ['QAT 16', 'Homam Ahmed', 0, 0],
    ['QAT 17', 'Tarek Salman', 0, 0],
    ['QAT 18', 'Abdulaziz Hatem', 0, 0],
    ['QAT 19', 'Ismaeel Mohammad', 0, 0],
    ['QAT 20', 'Saad Al-Sheeb', 0, 0],
    // 🇨🇭 SUIZA
    ['SUI 1', 'Escudo Suiza', 0, 0],
    ['SUI 2', 'Yann Sommer', 0, 0],
    ['SUI 3', 'Manuel Akanji', 0, 0],
    ['SUI 4', 'Fabian Schär', 0, 0],
    ['SUI 5', 'Ricardo Rodríguez', 0, 0],
    ['SUI 6', 'Silvan Widmer', 0, 0],
    ['SUI 7', 'Granit Xhaka', 0, 0],
    ['SUI 8', 'Remo Freuler', 0, 0],
    ['SUI 9', 'Michel Aebischer', 0, 0],
    ['SUI 10', 'Xherdan Shaqiri', 0, 0],
    ['SUI 11', 'Dan Ndoye', 0, 0],
    ['SUI 12', 'Ruben Vargas', 0, 0],
    ['SUI 13', 'Equipo Suiza', 0, 0],
    ['SUI 14', 'Breel Embolo', 0, 0],
    ['SUI 15', 'Kwadwo Duah', 0, 0],
    ['SUI 16', 'Zeki Amdouni', 0, 0],
    ['SUI 17', 'Denis Zakaria', 0, 0],
    ['SUI 18', 'Leonidas Stergiou', 0, 0],
    ['SUI 19', 'Vincent Sierro', 0, 0],
    ['SUI 20', 'Gregor Kobel', 0, 0],
    // 🇧🇷 BRASIL
    ['BRA 1', 'Escudo Brasil', 0, 0],
    ['BRA 2', 'Alisson Becker', 0, 0],
    ['BRA 3', 'Marquinhos', 0, 0],
    ['BRA 4', 'Gabriel Magalhães', 0, 0],
    ['BRA 5', 'Danilo', 0, 0],
    ['BRA 6', 'Guilherme Arana', 0, 0],
    ['BRA 7', 'Éder Militão', 0, 0],
    ['BRA 8', 'Bruno Guimarães', 0, 0],
    ['BRA 9', 'João Gomes', 0, 0],
    ['BRA 10', 'Lucas Paquetá', 0, 0],
    ['BRA 11', 'Douglas Luiz', 0, 0],
    ['BRA 12', 'Rodrygo Goes', 0, 0],
    ['BRA 13', 'Equipo Brasil', 0, 0],
    ['BRA 14', 'Vinícius Júnior', 0, 0],
    ['BRA 15', 'Raphinha', 0, 0],
    ['BRA 16', 'Endrick', 0, 0],
    ['BRA 17', 'Savinho', 0, 0],
    ['BRA 18', 'Gabriel Martinelli', 0, 0],
    ['BRA 19', 'Andreas Pereira', 0, 0],
    ['BRA 20', 'Ederson', 0, 0],
    // 🇲🇦 MARRUECOS
    ['MAR 1', 'Escudo Marruecos', 0, 0],
    ['MAR 2', 'Yassine Bounou', 0, 0],
    ['MAR 3', 'Achraf Hakimi', 0, 0],
    ['MAR 4', 'Nayef Aguerd', 0, 0],
    ['MAR 5', 'Romain Saïss', 0, 0],
    ['MAR 6', 'Yahia Attiyat Allah', 0, 0],
    ['MAR 7', 'Noussair Mazraoui', 0, 0],
    ['MAR 8', 'Sofyan Amrabat', 0, 0],
    ['MAR 9', 'Azzedine Ounahi', 0, 0],
    ['MAR 10', 'Bilal El Khannouss', 0, 0],
    ['MAR 11', 'Brahim Díaz', 0, 0],
    ['MAR 12', 'Hakim Ziyech', 0, 0],
    ['MAR 13', 'Equipo Marruecos', 0, 0],
    ['MAR 14', 'Amine Harit', 0, 0],
    ['MAR 15', 'Youssef En-Nesyri', 0, 0],
    ['MAR 16', 'Ayoub El Kaabi', 0, 0],
    ['MAR 17', 'Soufiane Rahimi', 0, 0],
    ['MAR 18', 'Chadi Riad', 0, 0],
    ['MAR 19', 'Abde Ezzalzouli', 0, 0],
    ['MAR 20', 'Munir Mohamedi', 0, 0],
    // 🇭🇹 HAITÍ
    ['HAI 1', 'Escudo Haití', 0, 0],
    ['HAI 2', 'Johny Placine', 0, 0],
    ['HAI 3', 'Carlens Arcus', 0, 0],
    ['HAI 4', 'Martin Expérience', 0, 0],
    ['HAI 5', 'Jean-Kévin Duverne', 0, 0],
    ['HAI 6', 'Ricardo Adé', 0, 0],
    ['HAI 7', 'Duke Lacroix', 0, 0],
    ['HAI 8', 'Garven Metusala', 0, 0],
    ['HAI 9', 'Hannes Delcroix', 0, 0],
    ['HAI 10', 'Leverton Pierre', 0, 0],
    ['HAI 11', 'Danley Jean Jacques', 0, 0],
    ['HAI 12', 'Jean-Ricner Bellearde', 0, 0],
    ['HAI 13', 'Equipo Haití', 0, 0],
    ['HAI 14', 'Christopher Attys', 0, 0],
    ['HAI 15', 'Derrick Etienne Jr.', 0, 0],
    ['HAI 16', 'Josué Casimir', 0, 0],
    ['HAI 17', 'Ruben Providence', 0, 0],
    ['HAI 18', 'Duckens Nazon', 0, 0],
    ['HAI 19', 'Louicius Deedson', 0, 0],
    ['HAI 20', 'Frantzdy Pierrot', 0, 0],
    // 🏴󠁧󠁢󠁳󠁣󠁴󠁿 ESCOCIA
    ['SCO 1', 'Escudo Escocia', 0, 0],
    ['SCO 2', 'Angus Gunn', 0, 0],
    ['SCO 3', 'Jack Hendry', 0, 0],
    ['SCO 4', 'Grant Hanley', 0, 0],
    ['SCO 5', 'Ryan Porteous', 0, 0],
    ['SCO 6', 'Andrew Robertson', 0, 0],
    ['SCO 7', 'Anthony Ralston', 0, 0],
    ['SCO 8', 'Callum McGregor', 0, 0],
    ['SCO 9', 'John McGinn', 0, 0],
    ['SCO 10', 'Scott McTominay', 0, 0],
    ['SCO 11', 'Billy Gilmour', 0, 0],
    ['SCO 12', 'Kenny McLean', 0, 0],
    ['SCO 13', 'Equipo Escocia', 0, 0],
    ['SCO 14', 'Che Adams', 0, 0],
    ['SCO 15', 'Lawrence Shankland', 0, 0],
    ['SCO 16', 'Ryan Christie', 0, 0],
    ['SCO 17', 'James Forrest', 0, 0],
    ['SCO 18', 'Scott McKenna', 0, 0],
    ['SCO 19', 'Greg Taylor', 0, 0],
    ['SCO 20', 'Liam Kelly', 0, 0],
    // 🇺🇸 ESTADOS UNIDOS
    ['USA 1', 'Escudo Estados Unidos', 0, 0],
    ['USA 2', 'Matt Turner', 0, 0],
    ['USA 3', 'Antonee Robinson', 0, 0],
    ['USA 4', 'Tim Ream', 0, 0],
    ['USA 5', 'Chris Richards', 0, 0],
    ['USA 6', 'Joe Scally', 0, 0],
    ['USA 7', 'Miles Robinson', 0, 0],
    ['USA 8', 'Weston McKennie', 0, 0],
    ['USA 9', 'Tyler Adams', 0, 0],
    ['USA 10', 'Yunus Musah', 0, 0],
    ['USA 11', 'Christian Pulisic', 0, 0],
    ['USA 12', 'Timothy Weah', 0, 0],
    ['USA 13', 'Equipo Estados Unidos', 0, 0],
    ['USA 14', 'Folarin Balogun', 0, 0],
    ['USA 15', 'Ricardo Pepi', 0, 0],
    ['USA 16', 'Gio Reyna', 0, 0],
    ['USA 17', 'Johnny Cardoso', 0, 0],
    ['USA 18', 'Malik Tillman', 0, 0],
    ['USA 19', 'Brenden Aaronson', 0, 0],
    ['USA 20', 'Ethan Horvath', 0, 0],
    // 🇵🇾 PARAGUAY
    ['PAR 1', 'Escudo Paraguay', 0, 0],
    ['PAR 2', 'Carlos Coronel', 0, 0],
    ['PAR 3', 'Gustavo Gómez', 0, 0],
    ['PAR 4', 'Omar Alderete', 0, 0],
    ['PAR 5', 'Fabián Balbuena', 0, 0],
    ['PAR 6', 'Junior Alonso', 0, 0],
    ['PAR 7', 'Matías Espinoza', 0, 0],
    ['PAR 8', 'Andrés Cubas', 0, 0],
    ['PAR 9', 'Mathías Villasanti', 0, 0],
    ['PAR 10', 'Diego Gómez', 0, 0],
    ['PAR 11', 'Damián Bobadilla', 0, 0],
    ['PAR 12', 'Alejandro Romero Gamarra', 0, 0],
    ['PAR 13', 'Equipo Paraguay', 0, 0],
    ['PAR 14', 'Miguel Almirón', 0, 0],
    ['PAR 15', 'Julio Enciso', 0, 0],
    ['PAR 16', 'Ramón Sosa', 0, 0],
    ['PAR 17', 'Adam Bareiro', 0, 0],
    ['PAR 18', 'Alex Arce', 0, 0],
    ['PAR 19', 'Ángel Romero', 0, 0],
    ['PAR 20', 'Gatito Fernández', 0, 0],
    // 🇦🇺 AUSTRALIA
    ['AUS 1', 'Escudo Australia', 0, 0],
    ['AUS 2', 'Mathew Ryan', 0, 0],
    ['AUS 3', 'Harry Souttar', 0, 0],
    ['AUS 4', 'Kye Rowles', 0, 0],
    ['AUS 5', 'Cameron Burgess', 0, 0],
    ['AUS 6', 'Aziz Behich', 0, 0],
    ['AUS 7', 'Gethin Jones', 0, 0],
    ['AUS 8', 'Jackson Irvine', 0, 0],
    ['AUS 9', 'Keanu Baccus', 0, 0],
    ['AUS 10', 'Connor Metcalfe', 0, 0],
    ['AUS 11', 'Riley McGree', 0, 0],
    ['AUS 12', 'Craig Goodwin', 0, 0],
    ['AUS 13', 'Equipo Australia', 0, 0],
    ['AUS 14', 'Mitchell Duke', 0, 0],
    ['AUS 15', 'Kusini Yengi', 0, 0],
    ['AUS 16', 'Martin Boyle', 0, 0],
    ['AUS 17', 'Jordy Bos', 0, 0],
    ['AUS 18', 'Lewis Miller', 0, 0],
    ['AUS 19', 'Aiden O\Neill', 0, 0],
    ['AUS 20', 'Joe Gauci', 0, 0],
    // 🇹🇷 TURQUÍA
    ['TUR 1', 'Escudo Turquía', 0, 0],
    ['TUR 2', 'Mert Günok', 0, 0],
    ['TUR 3', 'Samet Akaydin', 0, 0],
    ['TUR 4', 'Abdülkerim Bardakcı', 0, 0],
    ['TUR 5', 'Merih Demiral', 0, 0],
    ['TUR 6', 'Ferdi Kadıoğlu', 0, 0],
    ['TUR 7', 'Mert Müldür', 0, 0],
    ['TUR 8', 'Hakan Çalhanoğlu', 0, 0],
    ['TUR 9', 'Kaan Ayhan', 0, 0],
    ['TUR 10', 'Salih Özcan', 0, 0],
    ['TUR 11', 'Okay Yokuşlu', 0, 0],
    ['TUR 12', 'Arda Güler', 0, 0],
    ['TUR 13', 'Equipo Turquía', 0, 0],
    ['TUR 14', 'Kenan Yıldız', 0, 0],
    ['TUR 15', 'Barış Alper Yılmaz', 0, 0],
    ['TUR 16', 'Kerem Aktürkoğlu', 0, 0],
    ['TUR 17', 'Cenk Tosun', 0, 0],
    ['TUR 18', 'Zeki Çelik', 0, 0],
    ['TUR 19', 'İrfan Can Kahveci', 0, 0],
    ['TUR 20', 'Altay Bayındır', 0, 0],
    // 🇩🇪 ALEMANIA
    ['GER 1', 'Escudo Alemania', 0, 0],
    ['GER 2', 'Marc-André ter Stegen', 0, 0],
    ['GER 3', 'Antonio Rüdiger', 0, 0],
    ['GER 4', 'Jonathan Tah', 0, 0],
    ['GER 5', 'Nico Schlotterbeck', 0, 0],
    ['GER 6', 'David Raum', 0, 0],
    ['GER 7', 'Joshua Kimmich', 0, 0],
    ['GER 8', 'Robert Andrich', 0, 0],
    ['GER 9', 'Pascal Groß', 0, 0],
    ['GER 10', 'Florian Wirtz', 0, 0],
    ['GER 11', 'Jamal Musiala', 0, 0],
    ['GER 12', 'İlkay Gündoğan', 0, 0],
    ['GER 13', 'Equipo Alemania', 0, 0],
    ['GER 14', 'Kai Havertz', 0, 0],
    ['GER 15', 'Niclas Füllkrug', 0, 0],
    ['GER 16', 'Leroy Sané', 0, 0],
    ['GER 17', 'Thomas Müller', 0, 0],
    ['GER 18', 'Maximilian Mittelstädt', 0, 0],
    ['GER 19', 'Chris Führich', 0, 0],
    ['GER 20', 'Oliver Baumann', 0, 0],
    // 🇨🇼 CURAZAO
    ['CUW 1', 'Escudo Curazao', 0, 0],
    ['CUW 2', 'Eloy Room', 0, 0],
    ['CUW 3', 'Armando Obispo', 0, 0],
    ['CUW 4', 'Sherel Floranus', 0, 0],
    ['CUW 5', 'Juriën Gaari', 0, 0],
    ['CUW 6', 'Joshua Brenet', 0, 0],
    ['CUW 7', 'Roshon Van Eijma', 0, 0],
    ['CUW 8', 'Shurandy Sambo', 0, 0],
    ['CUW 9', 'Livano Comenencia', 0, 0],
    ['CUW 10', 'Godfried Roemeratoe', 0, 0],
    ['CUW 11', 'Juninho Bacuna', 0, 0],
    ['CUW 12', 'Leandro Bacuna', 0, 0],
    ['CUW 13', 'Equipo Curazao', 0, 0],
    ['CUW 14', 'Tahith Chong', 0, 0],
    ['CUW 15', 'Kenji Gorré', 0, 0],
    ['CUW 16', 'Jearl Margaritha', 0, 0],
    ['CUW 17', 'Jürgen Locadia', 0, 0],
    ['CUW 18', 'Jeremy Antonisse', 0, 0],
    ['CUW 19', 'Gervane Kastaneer', 0, 0],
    ['CUW 20', 'Sontje Hansen', 0, 0],
    // 🇨🇮 COSTA DE MARFIL
    ['CIV 1', 'Escudo Costa de Marfil', 0, 0],
    ['CIV 2', 'Yahia Fofana', 0, 0],
    ['CIV 3', 'Evan Ndicka', 0, 0],
    ['CIV 4', 'Ousmane Diomande', 0, 0],
    ['CIV 5', 'Willy Boly', 0, 0],
    ['CIV 6', 'Wilfried Singo', 0, 0],
    ['CIV 7', 'Ghislain Konan', 0, 0],
    ['CIV 8', 'Franck Kessié', 0, 0],
    ['CIV 9', 'Seko Fofana', 0, 0],
    ['CIV 10', 'Ibrahim Sangaré', 0, 0],
    ['CIV 11', 'Max Gradel', 0, 0],
    ['CIV 12', 'Simon Adingra', 0, 0],
    ['CIV 13', 'Equipo Costa de Marfil', 0, 0],
    ['CIV 14', 'Sébastien Haller', 0, 0],
    ['CIV 15', 'Oumar Diakité', 0, 0],
    ['CIV 16', 'Nicolas Pépé', 0, 0],
    ['CIV 17', 'Christian Kouamé', 0, 0],
    ['CIV 18', 'Odilon Kossounou', 0, 0],
    ['CIV 19', 'Jeremie Boga', 0, 0],
    ['CIV 20', 'Badra Ali Sangaré', 0, 0],
    // 🇪🇨 ECUADOR
    ['ECU 1', 'Escudo Ecuador', 0, 0],
    ['ECU 2', 'Alexander Domínguez', 0, 0],
    ['ECU 3', 'Piero Hincapié', 0, 0],
    ['ECU 4', 'Willian Pacho', 0, 0],
    ['ECU 5', 'Félix Torres', 0, 0],
    ['ECU 6', 'Ángelo Preciado', 0, 0],
    ['ECU 7', 'Pervis Estupiñán', 0, 0],
    ['ECU 8', 'Carlos Gruezo', 0, 0],
    ['ECU 9', 'Moises Caicedo', 0, 0],
    ['ECU 10', 'Alan Franco', 0, 0],
    ['ECU 11', 'Kendry Páez', 0, 0],
    ['ECU 12', 'Ángel Mena', 0, 0],
    ['ECU 13', 'Equipo Ecuador', 0, 0],
    ['ECU 14', 'Jeremy Sarmiento', 0, 0],
    ['ECU 15', 'Enner Valencia', 0, 0],
    ['ECU 16', 'Kevin Rodríguez', 0, 0],
    ['ECU 17', 'Jordy Caicedo', 0, 0],
    ['ECU 18', 'John Yeboah', 0, 0],
    ['ECU 19', 'Joao Ortiz', 0, 0],
    ['ECU 20', 'Hernán Galíndez', 0, 0],
    // 🇳🇱 PAÍSES BAJOS
    ['NED 1', 'Escudo Países Bajos', 0, 0],
    ['NED 2', 'Bart Verbruggen', 0, 0],
    ['NED 3', 'Virgil van Dijk', 0, 0],
    ['NED 4', 'Stefan de Vrij', 0, 0],
    ['NED 5', 'Nathan Aké', 0, 0],
    ['NED 6', 'Denzel Dumfries', 0, 0],
    ['NED 7', 'Jeremie Frimpong', 0, 0],
    ['NED 8', 'Tijjani Reijnders', 0, 0],
    ['NED 9', 'Jerdy Schouten', 0, 0],
    ['NED 10', 'Xavi Simons', 0, 0],
    ['NED 11', 'Cody Gakpo', 0, 0],
    ['NED 12', 'Memphis Depay', 0, 0],
    ['NED 13', 'Equipo Países Bajos', 0, 0],
    ['NED 14', 'Wout Weghorst', 0, 0],
    ['NED 15', 'Donyell Malen', 0, 0],
    ['NED 16', 'Joey Veerman', 0, 0],
    ['NED 17', 'Lutsharel Geertruida', 0, 0],
    ['NED 18', 'Micky van de Ven', 0, 0],
    ['NED 19', 'Georginio Wijnaldum', 0, 0],
    ['NED 20', 'Mark Flekken', 0, 0],
    // 🇯🇵 JAPÓN
    ['JPN 1', 'Escudo Japón', 0, 0],
    ['JPN 2', 'Zion Suzuki', 0, 0],
    ['JPN 3', 'Ko Itakura', 0, 0],
    ['JPN 4', 'Shogo Taniguchi', 0, 0],
    ['JPN 5', 'Takehiro Tomiyasu', 0, 0],
    ['JPN 6', 'Hiroki Ito', 0, 0],
    ['JPN 7', 'Yukinari Sugawara', 0, 0],
    ['JPN 8', 'Wataru Endo', 0, 0],
    ['JPN 9', 'Hidemasa Morita', 0, 0],
    ['JPN 10', 'Ao Tanaka', 0, 0],
    ['JPN 11', 'Takefusa Kubo', 0, 0],
    ['JPN 12', 'Takumi Minamino', 0, 0],
    ['JPN 13', 'Equipo Japón', 0, 0],
    ['JPN 14', 'Kaoru Mitoma', 0, 0],
    ['JPN 15', 'Ritsu Doan', 0, 0],
    ['JPN 16', 'Ayase Ueda', 0, 0],
    ['JPN 17', 'Takuma Asano', 0, 0],
    ['JPN 18', 'Keito Nakamura', 0, 0],
    ['JPN 19', 'Koki Ogawa', 0, 0],
    ['JPN 20', 'Keisuke Osako', 0, 0],
    // 🇸🇪 SUECIA
    ['SWE 1', 'Escudo Suecia', 0, 0],
    ['SWE 2', 'Robin Olsen', 0, 0],
    ['SWE 3', 'Victor Lindelöf', 0, 0],
    ['SWE 4', 'Isak Hien', 0, 0],
    ['SWE 5', 'Carl Starfelt', 0, 0],
    ['SWE 6', 'Ludwig Augustinsson', 0, 0],
    ['SWE 7', 'Emil Krafth', 0, 0],
    ['SWE 8', 'Dejan Kulusevski', 0, 0],
    ['SWE 9', 'Jens Cajuste', 0, 0],
    ['SWE 10', 'Anton Salétros', 0, 0],
    ['SWE 11', 'Emil Forsberg', 0, 0],
    ['SWE 12', 'Alexander Isak', 0, 0],
    ['SWE 13', 'Equipo Suecia', 0, 0],
    ['SWE 14', 'Viktor Gyökeres', 0, 0],
    ['SWE 15', 'Anthony Elanga', 0, 0],
    ['SWE 16', 'Gustaf Nilsson', 0, 0],
    ['SWE 17', 'Hugo Larsson', 0, 0],
    ['SWE 18', 'Samuel Dahl', 0, 0],
    ['SWE 19', 'Linus Wahlqvist', 0, 0],
    ['SWE 20', 'Viktor Johansson', 0, 0],
    // 🇹🇳 TÚNEZ
    ['TUN 1', 'Escudo Túnez', 0, 0],
    ['TUN 2', 'Bechir Ben Saïd', 0, 0],
    ['TUN 3', 'Yassine Meriah', 0, 0],
    ['TUN 4', 'Montassar Talbi', 0, 0],
    ['TUN 5', 'Dylan Bronn', 0, 0],
    ['TUN 6', 'Ali Abdi', 0, 0],
    ['TUN 7', 'Yan Valery', 0, 0],
    ['TUN 8', 'Ellyes Skhiri', 0, 0],
    ['TUN 9', 'Aïssa Laïdouni', 0, 0],
    ['TUN 10', 'Mohamed Ali Ben Romdhane', 0, 0],
    ['TUN 11', 'Hamza Rafia', 0, 0],
    ['TUN 12', 'Anis Ben Slimane', 0, 0],
    ['TUN 13', 'Equipo Túnez', 0, 0],
    ['TUN 14', 'Youssef Msakni', 0, 0],
    ['TUN 15', 'Elias Achouri', 0, 0],
    ['TUN 16', 'Sayfallah Ltaief', 0, 0],
    ['TUN 17', 'Seifeddine Jaziri', 0, 0],
    ['TUN 18', 'Wajdi Kechrida', 0, 0],
    ['TUN 19', 'Nader Ghandri', 0, 0],
    ['TUN 20', 'Amenallah Memmiche', 0, 0],
    // 🇧🇪 BÉLGICA
    ['BEL 1', 'Escudo Bélgica', 0, 0],
    ['BEL 2', 'Koen Casteels', 0, 0],
    ['BEL 3', 'Wout Faes', 0, 0],
    ['BEL 4', 'Jan Vertonghen', 0, 0],
    ['BEL 5', 'Timothy Castagne', 0, 0],
    ['BEL 6', 'Arthur Theate', 0, 0],
    ['BEL 7', 'Amadou Onana', 0, 0],
    ['BEL 8', 'Orel Mangala', 0, 0],
    ['BEL 9', 'Kevin De Bruyne', 0, 0],
    ['BEL 10', 'Youri Tielemans', 0, 0],
    ['BEL 11', 'Romelu Lukaku', 0, 0],
    ['BEL 12', 'Jérémy Doku', 0, 0],
    ['BEL 13', 'Equipo Bélgica', 0, 0],
    ['BEL 14', 'Leandro Trossard', 0, 0],
    ['BEL 15', 'Dodi Lukebakio', 0, 0],
    ['BEL 16', 'Johan Bakayoko', 0, 0],
    ['BEL 17', 'Charles De Ketelaere', 0, 0],
    ['BEL 18', 'Zeno Debast', 0, 0],
    ['BEL 19', 'Maxim De Cuyper', 0, 0],
    ['BEL 20', 'Thomas Kaminski', 0, 0],
    // 🇪🇬 EGIPTO
    ['EGY 1', 'Escudo Egipto', 0, 0],
    ['EGY 2', 'Mohamed El Shenawy', 0, 0],
    ['EGY 3', 'Mohamed Abdelmonem', 0, 0],
    ['EGY 4', 'Ahmed Hegazi', 0, 0],
    ['EGY 5', 'Mohamed Hany', 0, 0],
    ['EGY 6', 'Mohamed Hamdi', 0, 0],
    ['EGY 7', 'Marwan Attia', 0, 0],
    ['EGY 8', 'Hamdi Fathi', 0, 0],
    ['EGY 9', 'Imam Ashour', 0, 0],
    ['EGY 10', 'Mohamed Elneny', 0, 0],
    ['EGY 11', 'Zizo', 0, 0],
    ['EGY 12', 'Mohamed Salah', 0, 0],
    ['EGY 13', 'Equipo Egipto', 0, 0],
    ['EGY 14', 'Mostafa Mohamed', 0, 0],
    ['EGY 15', 'Trézéguet', 0, 0],
    ['EGY 16', 'Omar Marmoush', 0, 0],
    ['EGY 17', 'Koka', 0, 0],
    ['EGY 18', 'Rami Rabia', 0, 0],
    ['EGY 19', 'Mostafa Shobeir', 0, 0],
    ['EGY 20', 'Mohamed Awad', 0, 0],
    // 🇮🇷 IRÁN
    ['IRN 1', 'Escudo Irán', 0, 0],
    ['IRN 2', 'Alireza Beiranvand', 0, 0],
    ['IRN 3', 'Shojae Khalilzadeh', 0, 0],
    ['IRN 4', 'Hossein Kanaani', 0, 0],
    ['IRN 5', 'Milad Mohammadi', 0, 0],
    ['IRN 6', 'Ramin Rezaeian', 0, 0],
    ['IRN 7', 'Saman Ghoddos', 0, 0],
    ['IRN 8', 'Saeid Ezatolahi', 0, 0],
    ['IRN 9', 'Alireza Jahanbakhsh', 0, 0],
    ['IRN 10', 'Mehdi Torabi', 0, 0],
    ['IRN 11', 'Ali Gholizadeh', 0, 0],
    ['IRN 12', 'Mehdi Taremi', 0, 0],
    ['IRN 13', 'Equipo Irán', 0, 0],
    ['IRN 14', 'Sardar Azmoun', 0, 0],
    ['IRN 15', 'Shahriyar Moghanlou', 0, 0],
    ['IRN 16', 'Omid Noorafkan', 0, 0],
    ['IRN 17', 'Ehsan Hajsafi', 0, 0],
    ['IRN 18', 'Majid Hosseini', 0, 0],
    ['IRN 19', 'Rouzbeh Cheshmi', 0, 0],
    ['IRN 20', 'Payam Niazmand', 0, 0],
    // 🇳🇿 NUEVA ZELANDA
    ['NZL 1', 'Escudo Nueva Zelanda', 0, 0],
    ['NZL 2', 'Alex Paulsen', 0, 0],
    ['NZL 3', 'Michael Boxall', 0, 0],
    ['NZL 4', 'Liberato Cacace', 0, 0],
    ['NZL 5', 'Tyler Bindon', 0, 0],
    ['NZL 6', 'Tommy Smith', 0, 0],
    ['NZL 7', 'Tim Payne', 0, 0],
    ['NZL 8', 'Joe Bell', 0, 0],
    ['NZL 9', 'Matthew Garbett', 0, 0],
    ['NZL 10', 'Marko Stamenić', 0, 0],
    ['NZL 11', 'Sarpreet Singh', 0, 0],
    ['NZL 12', 'Chris Wood', 0, 0],
    ['NZL 13', 'Equipo Nueva Zelanda', 0, 0],
    ['NZL 14', 'Ben Waine', 0, 0],
    ['NZL 15', 'Kosta Barbarouses', 0, 0],
    ['NZL 16', 'Elijah Just', 0, 0],
    ['NZL 17', 'Callum McCowatt', 0, 0],
    ['NZL 18', 'Nando Pijnaker', 0, 0],
    ['NZL 19', 'Dalton Wilkins', 0, 0],
    ['NZL 20', 'Oliver Sail', 0, 0],
    // 🇪🇸 ESPAÑA
    ['ESP 1', 'Escudo España', 0, 0],
    ['ESP 2', 'Unai Simón', 0, 0],
    ['ESP 3', 'Robin Le Normand', 0, 0],
    ['ESP 4', 'Aymeric Laporte', 0, 0],
    ['ESP 5', 'Dani Carvajal', 0, 0],
    ['ESP 6', 'Marc Cucurella', 0, 0],
    ['ESP 7', 'Rodri Hernández', 0, 0],
    ['ESP 8', 'Fabián Ruiz', 0, 0],
    ['ESP 9', 'Pedri González', 0, 0],
    ['ESP 10', 'Dani Olmo', 0, 0],
    ['ESP 11', 'Lamine Yamal', 0, 0],
    ['ESP 12', 'Nico Williams', 0, 0],
    ['ESP 13', 'Equipo España', 0, 0],
    ['ESP 14', 'Álvaro Morata', 0, 0],
    ['ESP 15', 'Mikel Oyarzabal', 0, 0],
    ['ESP 16', 'Alejandro Grimaldo', 0, 0],
    ['ESP 17', 'Martin Zubimendi', 0, 0],
    ['ESP 18', 'Ferran Torres', 0, 0],
    ['ESP 19', 'Jesús Navas', 0, 0],
    ['ESP 20', 'David Raya', 0, 0],
    // 🇨🇻 CABO VERDE
    ['CPV 1', 'Escudo Cabo Verde', 0, 0],
    ['CPV 2', 'Vozinha', 0, 0],
    ['CPV 3', 'Logan Costa', 0, 0],
    ['CPV 4', 'Roberto Lopes', 0, 0],
    ['CPV 5', 'Stopira', 0, 0],
    ['CPV 6', 'Steven Moreira', 0, 0],
    ['CPV 7', 'João Paulo Fernandes', 0, 0],
    ['CPV 8', 'Kevin Pina', 0, 0],
    ['CPV 9', 'Jamiro Monteiro', 0, 0],
    ['CPV 10', 'Kenny Rocha Santos', 0, 0],
    ['CPV 11', 'Deroy Duarte', 0, 0],
    ['CPV 12', 'Patrick Andrade', 0, 0],
    ['CPV 13', 'Equipo Cabo Verde', 0, 0],
    ['CPV 14', 'Ryan Mendes', 0, 0],
    ['CPV 15', 'Garry Rodrigues', 0, 0],
    ['CPV 16', 'Bebé', 0, 0],
    ['CPV 17', 'Jovane Cabral', 0, 0],
    ['CPV 18', 'Gilson Tavares', 0, 0],
    ['CPV 19', 'Diney Borges', 0, 0],
    ['CPV 20', 'Dylan Silva', 0, 0],
    // 🇸🇦 ARABIA SAUDITA
    ['KSA 1', 'Escudo Arabia S.', 0, 0],
    ['KSA 2', 'Mohammed Al-Owais', 0, 0],
    ['KSA 3', 'Ali Lajami', 0, 0],
    ['KSA 4', 'Ali Al-Bulaihi', 0, 0],
    ['KSA 5', 'Saud Abdulhamid', 0, 0],
    ['KSA 6', 'Yasir Al-Shahrani', 0, 0],
    ['KSA 7', 'Hassan Tambakti', 0, 0],
    ['KSA 8', 'Mohamed Kanno', 0, 0],
    ['KSA 9', 'Abdullah Al-Khaibari', 0, 0],
    ['KSA 10', 'Faisal Al-Ghamdi', 0, 0],
    ['KSA 11', 'Musab Al-Juwayr', 0, 0],
    ['KSA 12', 'Salem Al-Dawsari', 0, 0],
    ['KSA 13', 'Equipo Arabia S.', 0, 0],
    ['KSA 14', 'Firas Al-Buraikan', 0, 0],
    ['KSA 15', 'Saleh Al-Shehri', 0, 0],
    ['KSA 16', 'Abdulrahman Ghareeb', 0, 0],
    ['KSA 17', 'Ayman Ahmed', 0, 0],
    ['KSA 18', 'Sultan Al-Ghannam', 0, 0],
    ['KSA 19', 'Abdulelah Al-Malki', 0, 0],
    ['KSA 20', 'Ahmed Al-Kassar', 0, 0],
    // 🇺🇾 URUGUAY
    ['URU 1', 'Escudo Uruguay', 0, 0],
    ['URU 2', 'Sergio Rochet', 0, 0],
    ['URU 3', 'José María Giménez', 0, 0],
    ['URU 4', 'Ronald Araújo', 0, 0],
    ['URU 5', 'Mathías Olivera', 0, 0],
    ['URU 6', 'Matías Viña', 0, 0],
    ['URU 7', 'Guillermo Varela', 0, 0],
    ['URU 8', 'Federico Valverde', 0, 0],
    ['URU 9', 'Rodrigo Bentancur', 0, 0],
    ['URU 10', 'Manuel Ugarte', 0, 0],
    ['URU 11', 'Nicolas de la Cruz', 0, 0],
    ['URU 12', 'Giorgian de Arrascaeta', 0, 0],
    ['URU 13', 'Equipo Uruguay', 0, 0],
    ['URU 14', 'Darwin Núñez', 0, 0],
    ['URU 15', 'Facundo Pellistri', 0, 0],
    ['URU 16', 'Maximiliano Araújo', 0, 0],
    ['URU 17', 'Brian Rodríguez', 0, 0],
    ['URU 18', 'Facundo Torres', 0, 0],
    ['URU 19', 'Luciano Rodríguez', 0, 0],
    ['URU 20', 'Santiago Mele', 0, 0],
    // 🇫🇷 FRANCIA
    ['FRA 1', 'Escudo Francia', 0, 0],
    ['FRA 2', 'Mike Maignan', 0, 0],
    ['FRA 3', 'William Saliba', 0, 0],
    ['FRA 4', 'Dayot Upamecano', 0, 0],
    ['FRA 5', 'Jules Koundé', 0, 0],
    ['FRA 6', 'Theo Hernández', 0, 0],
    ['FRA 7', 'Aurélien Tchouaméni', 0, 0],
    ['FRA 8', 'Eduardo Camavinga', 0, 0],
    ['FRA 9', 'N\Golo Kanté', 0, 0],
    ['FRA 10', 'Antoine Griezmann', 0, 0],
    ['FRA 11', 'Kylian Mbappé', 0, 0],
    ['FRA 12', 'Ousmane Dembélé', 0, 0],
    ['FRA 13', 'Equipo Francia', 0, 0],
    ['FRA 14', 'Marcus Thuram', 0, 0],
    ['FRA 15', 'Bradley Barcola', 0, 0],
    ['FRA 16', 'Ibrahima Konaté', 0, 0],
    ['FRA 17', 'Adrien Rabiot', 0, 0],
    ['FRA 18', 'Warren Zaïre-Emery', 0, 0],
    ['FRA 19', 'Olivier Giroud', 0, 0],
    ['FRA 20', 'Brice Samba', 0, 0],
    // 🇸🇳 SENEGAL
    ['SEN 1', 'Escudo Senegal', 0, 0],
    ['SEN 2', 'Édouard Mendy', 0, 0],
    ['SEN 3', 'Kalidou Koulibaly', 0, 0],
    ['SEN 4', 'Abdou Diallo', 0, 0],
    ['SEN 5', 'Moussa Niakhaté', 0, 0],
    ['SEN 6', 'Ismaïlak Jakobs', 0, 0],
    ['SEN 7', 'Formose Mendy', 0, 0],
    ['SEN 8', 'Idrissa Gueye', 0, 0],
    ['SEN 9', 'Lamine Camara', 0, 0],
    ['SEN 10', 'Pape Matar Sarr', 0, 0],
    ['SEN 11', 'Nampalys Mendy', 0, 0],
    ['SEN 12', 'Pathé Ciss', 0, 0],
    ['SEN 13', 'Equipo Senegal', 0, 0],
    ['SEN 14', 'Sadio Mané', 0, 0],
    ['SEN 15', 'Ismaïla Sarr', 0, 0],
    ['SEN 16', 'Nicolas Jackson', 0, 0],
    ['SEN 17', 'Iliman Ndiaye', 0, 0],
    ['SEN 18', 'Habib Diallo', 0, 0],
    ['SEN 19', 'Abdoulaye Seck', 0, 0],
    ['SEN 20', 'Mory Diaw', 0, 0],
    // 🇦🇪 EMIRATOS ÁRABES UNIDOS / IRAK
    ['IRQ 1', 'Escudo Irak/EAU', 0, 0],
    ['IRQ 2', 'Jalal Hassan', 0, 0],
    ['IRQ 3', 'Rebin Sulaka', 0, 0],
    ['IRQ 4', 'Saad Natiq', 0, 0],
    ['IRQ 5', 'Hussein Ali', 0, 0],
    ['IRQ 6', 'Merdhas Doski', 0, 0],
    ['IRQ 7', 'Zaid Tahseen', 0, 0],
    ['IRQ 8', 'Amir Al-Ammari', 0, 0],
    ['IRQ 9', 'Osama Rashid', 0, 0],
    ['IRQ 10', 'Ibrahim Bayesh', 0, 0],
    ['IRQ 11', 'Youssef Amyn', 0, 0],
    ['IRQ 12', 'Ali Jasim', 0, 0],
    ['IRQ 13', 'Equipo Irak/EAU', 0, 0],
    ['IRQ 14', 'Zidane Iqbal', 0, 0],
    ['IRQ 15', 'Aymen Hussein', 0, 0],
    ['IRQ 16', 'Mohanad Ali', 0, 0],
    ['IRQ 17', 'Montader Madjed', 0, 0],
    ['IRQ 18', 'Bashar Resan', 0, 0],
    ['IRQ 19', 'Frans Putros', 0, 0],
    ['IRQ 20', 'Ahmed Basil', 0, 0],
    // 🇳🇴 NORUEGA
    ['NOR 1', 'Escudo Noruega', 0, 0],
    ['NOR 2', 'Ørjan Nyland', 0, 0],
    ['NOR 3', 'Leo Østigård', 0, 0],
    ['NOR 4', 'Kristoffer Ajer', 0, 0],
    ['NOR 5', 'Andreas Hanche-Olsen', 0, 0],
    ['NOR 6', 'Julian Ryerson', 0, 0],
    ['NOR 7', 'Martin Ødegaard', 0, 0],
    ['NOR 8', 'Sander Berge', 0, 0],
    ['NOR 9', 'Patrick Berg', 0, 0],
    ['NOR 10', 'Morton Thorsby', 0, 0],
    ['NOR 11', 'Erling Haaland', 0, 0],
    ['NOR 12', 'Alexander Sørloth', 0, 0],
    ['NOR 13', 'Equipo Noruega', 0, 0],
    ['NOR 14', 'Jørgen Strand Larsen', 0, 0],
    ['NOR 15', 'Antonio Nusa', 0, 0],
    ['NOR 16', 'Oscar Bobb', 0, 0],
    ['NOR 17', 'David Møller Wolfe', 0, 0],
    ['NOR 18', 'Marcus Holmgren Pedersen', 0, 0],
    ['NOR 19', 'Kristian Thorstvedt', 0, 0],
    ['NOR 20', 'Mathias Dyngeland', 0, 0],
    // 🇦🇷 ARGENTINA
    ['ARG 1', 'Escudo Argentina', 0, 0],
    ['ARG 2', 'Emiliano Martínez', 0, 0],
    ['ARG 3', 'Cristian Romero', 0, 0],
    ['ARG 4', 'Lisandro Martínez', 0, 0],
    ['ARG 5', 'Nahuel Molina', 0, 0],
    ['ARG 6', 'Nicolás Tagliafico', 0, 0],
    ['ARG 7', 'Gonzalo Montiel', 0, 0],
    ['ARG 8', 'Rodrigo De Paul', 0, 0],
    ['ARG 9', 'Enzo Fernández', 0, 0],
    ['ARG 10', 'Alexis Mac Allister', 0, 0],
    ['ARG 11', 'Leandro Paredes', 0, 0],
    ['ARG 12', 'Lionel Messi', 0, 0],
    ['ARG 13', 'Equipo Argentina', 0, 0],
    ['ARG 14', 'Giovani Lo Celso', 0, 0],
    ['ARG 15', 'Julián Álvarez', 0, 0],
    ['ARG 16', 'Lautaro Martínez', 0, 0],
    ['ARG 17', 'Alejandro Garnacho', 0, 0],
    ['ARG 18', 'Nicolás González', 0, 0],
    ['ARG 19', 'Exequiel Palacios', 0, 0],
    ['ARG 20', 'Geronimo Rulli', 0, 0],
    // 🇩🇿 ARGELIA
    ['ALG 1', 'Escudo Argelia', 0, 0],
    ['ALG 2', 'Anthony Mandrea', 0, 0],
    ['ALG 3', 'Aïssa Mandi', 0, 0],
    ['ALG 4', 'Ramy Bensebaini', 0, 0],
    ['ALG 5', 'Rayan Aït-Nouri', 0, 0],
    ['ALG 6', 'Youcef Atal', 0, 0],
    ['ALG 7', 'Mohamed Amine Tougai', 0, 0],
    ['ALG 8', 'Ismaël Bennacer', 0, 0],
    ['ALG 9', 'Ramiz Zerrouki', 0, 0],
    ['ALG 10', 'Houssem Aouar', 0, 0],
    ['ALG 11', 'Nabil Bentaleb', 0, 0],
    ['ALG 12', 'Riyad Mahrez', 0, 0],
    ['ALG 13', 'Equipo Argelia', 0, 0],
    ['ALG 14', 'Said Benrahma', 0, 0],
    ['ALG 15', 'Amine Gouiri', 0, 0],
    ['ALG 16', 'Baghdad Bounedjah', 0, 0],
    ['ALG 17', 'Mohamed Amoura', 0, 0],
    ['ALG 18', 'Farès Chaïbi', 0, 0],
    ['ALG 19', 'Kevin Van Den Kerkhof', 0, 0],
    ['ALG 20', 'Mustapha Zeghba', 0, 0],
    // 🇦🇹 AUSTRIA
    ['AUT 1', 'Escudo Austria', 0, 0],
    ['AUT 2', 'Patrick Pentz', 0, 0],
    ['AUT 3', 'Kevin Danso', 0, 0],
    ['AUT 4', 'Maximilian Wöber', 0, 0],
    ['AUT 5', 'Philipp Lienhart', 0, 0],
    ['AUT 6', 'Stefan Posch', 0, 0],
    ['AUT 7', 'Marcel Sabitzer', 0, 0],
    ['AUT 8', 'Konrad Laimer', 0, 0],
    ['AUT 9', 'Nicolas Seiwald', 0, 0],
    ['AUT 10', 'Florian Grillitsch', 0, 0],
    ['AUT 11', 'Christoph Baumgartner', 0, 0],
    ['AUT 12', 'Patrick Wimmer', 0, 0],
    ['AUT 13', 'Equipo Austria', 0, 0],
    ['AUT 14', 'Romano Schmid', 0, 0],
    ['AUT 15', 'Michael Gregoritsch', 0, 0],
    ['AUT 16', 'Marko Arnautović', 0, 0],
    ['AUT 17', 'Andreas Weimann', 0, 0],
    ['AUT 18', 'Phillipp Mwene', 0, 0],
    ['AUT 19', 'Gernot Trauner', 0, 0],
    ['AUT 20', 'Heinz Lindner', 0, 0],
    // 🇯🇴 JORDANIA
    ['JOR 1', 'Escudo Jordania', 0, 0],
    ['JOR 2', 'Yazeed Abulaila', 0, 0],
    ['JOR 3', 'Yazan Al-Arab', 0, 0],
    ['JOR 4', 'Abdallah Nasib', 0, 0],
    ['JOR 5', 'Salem Al-Ajalin', 0, 0],
    ['JOR 6', 'Ihsan Haddad', 0, 0],
    ['JOR 7', 'Mohammad Abu Hachich', 0, 0],
    ['JOR 8', 'Nizar Al-Rashdan', 0, 0],
    ['JOR 9', 'Noor Al-Rawabdeh', 0, 0],
    ['JOR 10', 'Raja\ei Ayed', 0, 0],
    ['JOR 11', 'Mousa Al-Tamari', 0, 0],
    ['JOR 12', 'Ali Olwan', 0, 0],
    ['JOR 13', 'Equipo Jordania', 0, 0],
    ['JOR 14', 'Yazan Al-Naimat', 0, 0],
    ['JOR 15', 'Mahmoud Al-Mardi', 0, 0],
    ['JOR 16', 'Anas Al-Abarat', 0, 0],
    ['JOR 17', 'Bara\ Marei', 0, 0],
    ['JOR 18', 'Firas Shelbaieh', 0, 0],
    ['JOR 19', 'Ibrahim Sadeh', 0, 0],
    ['JOR 20', 'Abdallah Al-Fakhouri', 0, 0],
    // 🇵🇹 PORTUGAL
    ['POR 1', 'Escudo Portugal', 0, 0],
    ['POR 2', 'Diogo Costa', 0, 0],
    ['POR 3', 'Rúben Dias', 0, 0],
    ['POR 4', 'Pepe', 0, 0],
    ['POR 5', 'João Cancelo', 0, 0],
    ['POR 6', 'Nuno Mendes', 0, 0],
    ['POR 7', 'João Palhinha', 0, 0],
    ['POR 8', 'Vitinha', 0, 0],
    ['POR 9', 'Bruno Fernandes', 0, 0],
    ['POR 10', 'Bernardo Silva', 0, 0],
    ['POR 11', 'Cristiano Ronaldo', 0, 0],
    ['POR 12', 'Rafael Leão', 0, 0],
    ['POR 13', 'Equipo Portugal', 0, 0],
    ['POR 14', 'João Félix', 0, 0],
    ['POR 15', 'Gonçalo Ramos', 0, 0],
    ['POR 16', 'Diogo Jota', 0, 0],
    ['POR 17', 'Rúben Neves', 0, 0],
    ['POR 18', 'João Neves', 0, 0],
    ['POR 19', 'Diogo Dalot', 0, 0],
    ['POR 20', 'José Sá', 0, 0],
    // 🇨🇩 RD CONGO
    ['COD 1', 'Escudo RD Congo', 0, 0],
    ['COD 2', 'Dimitry Bertaud', 0, 0],
    ['COD 3', 'Chancel Mbemba', 0, 0],
    ['COD 4', 'Henoc Inonga', 0, 0],
    ['COD 5', 'Dylan Batubinsika', 0, 0],
    ['COD 6', 'Arthur Masuaku', 0, 0],
    ['COD 7', 'Gédéon Kalulu', 0, 0],
    ['COD 8', 'Samuel Moutoussamy', 0, 0],
    ['COD 9', 'Charles Pickel', 0, 0],
    ['COD 10', 'Edo Kayembe', 0, 0],
    ['COD 11', 'Meschack Elia', 0, 0],
    ['COD 12', 'Yoane Wissa', 0, 0],
    ['COD 13', 'Equipo RD Congo', 0, 0],
    ['COD 14', 'Théo Bongonda', 0, 0],
    ['COD 15', 'Cédric Bakambu', 0, 0],
    ['COD 16', 'Simon Banza', 0, 0],
    ['COD 17', 'Fiston Mayele', 0, 0],
    ['COD 18', 'Joris Kayembe', 0, 0],
    ['COD 19', 'Rocky Bushiri', 0, 0],
    ['COD 20', 'Lionel Mpasi', 0, 0],
    // 🇺🇿 UZBEKISTÁN
    ['UZB 1', 'Escudo Uzbekistán', 0, 0],
    ['UZB 2', 'Utkir Yusupov', 0, 0],
    ['UZB 3', 'Abdukodir Khusanov', 0, 0],
    ['UZB 4', 'Rustam Ashurmatov', 0, 0],
    ['UZB 5', 'Umar Eshmurodov', 0, 0],
    ['UZB 6', 'Sherzod Nasrullaev', 0, 0],
    ['UZB 7', 'Farrukh Sayfiev', 0, 0],
    ['UZB 8', 'Otabek Shukurov', 0, 0],
    ['UZB 9', 'Odiljon Hamrobekov', 0, 0],
    ['UZB 10', 'Jaloliddin Masharipov', 0, 0],
    ['UZB 11', 'Abbosbek Fayzullaev', 0, 0],
    ['UZB 12', 'Eldor Shomurodov', 0, 0],
    ['UZB 13', 'Equipo Uzbekistán', 0, 0],
    ['UZB 14', 'Oston Urunov', 0, 0],
    ['UZB 15', 'Igor Sergeev', 0, 0],
    ['UZB 16', 'Khozhimat Erkinov', 0, 0],
    ['UZB 17', 'Jamshid Iskanderov', 0, 0],
    ['UZB 18', 'Husniddin Aliqulov', 0, 0],
    ['UZB 19', 'Azizbek Turgunboev', 0, 0],
    ['UZB 20', 'Abduvohid Nematov', 0, 0],
    // 🇨🇴 COLOMBIA
    ['COL 1', 'Escudo Colombia', 0, 0],
    ['COL 2', 'Camilo Vargas', 0, 0],
    ['COL 3', 'Dávinson Sánchez', 0, 0],
    ['COL 4', 'Jhon Lucumí', 0, 0],
    ['COL 5', 'Daniel Muñoz', 0, 0],
    ['COL 6', 'Johan Mojica', 0, 0],
    ['COL 7', 'Yerry Mina', 0, 0],
    ['COL 8', 'Santiago Arias', 0, 0],
    ['COL 9', 'Jefferson Lerma', 0, 0],
    ['COL 10', 'Richard Ríos', 0, 0],
    ['COL 11', 'Jhon Arias', 0, 0],
    ['COL 12', 'James Rodríguez', 0, 0],
    ['COL 13', 'Equipo Colombia', 0, 0],
    ['COL 14', 'Mateus Uribe', 0, 0],
    ['COL 15', 'Luis Díaz', 0, 0],
    ['COL 16', 'Jhon Córdoba', 0, 0],
    ['COL 17', 'Luis Sinisterra', 0, 0],
    ['COL 18', 'Jhon Durán', 0, 0],
    ['COL 19', 'Juan Fernando Quintero', 0, 0],
    ['COL 20', 'David Ospina', 0, 0],
    // 🏴󠁧󠁢󠁥󠁮󠁧󠁿 INGLATERRA
    ['ENG 1', 'Escudo Inglaterra', 0, 0],
    ['ENG 2', 'Jordan Pickford', 0, 0],
    ['ENG 3', 'John Stones', 0, 0],
    ['ENG 4', 'Marc Guéhi', 0, 0],
    ['ENG 5', 'Kyle Walker', 0, 0],
    ['ENG 6', 'Kieran Trippier', 0, 0],
    ['ENG 7', 'Declan Rice', 0, 0],
    ['ENG 8', 'Trent Alexander-Arnold', 0, 0],
    ['ENG 9', 'Jude Bellingham', 0, 0],
    ['ENG 10', 'Phil Foden', 0, 0],
    ['ENG 11', 'Bukayo Saka', 0, 0],
    ['ENG 12', 'Harry Kane', 0, 0],
    ['ENG 13', 'Equipo Inglaterra', 0, 0],
    ['ENG 14', 'Cole Palmer', 0, 0],
    ['ENG 15', 'Kobbie Mainoo', 0, 0],
    ['ENG 16', 'Ollie Watkins', 0, 0],
    ['ENG 17', 'Anthony Gordon', 0, 0],
    ['ENG 18', 'Ezri Konsa', 0, 0],
    ['ENG 19', 'Luke Shaw', 0, 0],
    ['ENG 20', 'Aaron Ramsdale', 0, 0],
    // 🇭🇷 CROACIA
    ['CRO 1', 'Escudo Croacia', 0, 0],
    ['CRO 2', 'Dominik Livaković', 0, 0],
    ['CRO 3', 'Joško Gvardiol', 0, 0],
    ['CRO 4', 'Josip Šutalo', 0, 0],
    ['CRO 5', 'Domagoj Vida', 0, 0],
    ['CRO 6', 'Josip Stanišić', 0, 0],
    ['CRO 7', 'Luka Modrić', 0, 0],
    ['CRO 8', 'Mateo Kovačić', 0, 0],
    ['CRO 9', 'Marcelo Brozović', 0, 0],
    ['CRO 10', 'Mario Pašalić', 0, 0],
    ['CRO 11', 'Lovro Majer', 0, 0],
    ['CRO 12', 'Luka Sučić', 0, 0],
    ['CRO 13', 'Equipo Croacia', 0, 0],
    ['CRO 14', 'Ivan Perišić', 0, 0],
    ['CRO 15', 'Andrej Kramarić', 0, 0],
    ['CRO 16', 'Bruno Petković', 0, 0],
    ['CRO 17', 'Ante Budimir', 0, 0],
    ['CRO 18', 'Borna Sosa', 0, 0],
    ['CRO 19', 'Josip Juranović', 0, 0],
    ['CRO 20', 'Nediljko Labrović', 0, 0],
    // 🇬🇭 GHANA
    ['GHA 1', 'Escudo Ghana', 0, 0],
    ['GHA 2', 'Lawrence Ati-Zigi', 0, 0],
    ['GHA 3', 'Mohammed Salisu', 0, 0],
    ['GHA 4', 'Alexander Djiku', 0, 0],
    ['GHA 5', 'Alidu Seidu', 0, 0],
    ['GHA 6', 'Gideon Mensah', 0, 0],
    ['GHA 7', 'Tariq Lamptey', 0, 0],
    ['GHA 8', 'Thomas Partey', 0, 0],
    ['GHA 9', 'Salo Abdul Samed', 0, 0],
    ['GHA 10', 'Elisha Owusu', 0, 0],
    ['GHA 11', 'Mohammed Kudus', 0, 0],
    ['GHA 12', 'Jordan Ayew', 0, 0],
    ['GHA 13', 'Equipo Ghana', 0, 0],
    ['GHA 14', 'Inaki Williams', 0, 0],
    ['GHA 15', 'Antoine Semenyo', 0, 0],
    ['GHA 16', 'Ernest Nuamah', 0, 0],
    ['GHA 17', 'Abdul Fatawu Issahaku', 0, 0],
    ['GHA 18', 'Denis Odoi', 0, 0],
    ['GHA 19', 'Joseph Wollacott', 0, 0],
    ['GHA 20', 'Manaf Nurudeen', 0, 0],
    // 🇵🇦 PANAMA
    ['PAN 1', 'Escudo Panama', 0, 0],
    ['PAN 2', 'Orlando Mosquera', 0, 0],
    ['PAN 3', 'Luis Mejía', 0, 0],
    ['PAN 4', 'Fidel Escobar', 0, 0],
    ['PAN 5', 'Andrés Andrade', 0, 0],
    ['PAN 6', 'Michael Amir Murillo', 0, 0],
    ['PAN 7', 'Eric Davis', 0, 0],
    ['PAN 8', 'José Córdoba', 0, 0],
    ['PAN 9', 'César Blackman', 0, 0],
    ['PAN 10', 'Cristian Martínez', 0, 0],
    ['PAN 11', 'Aníbal Godoy', 0, 0],
    ['PAN 12', 'Adalberto Carrasquilla', 0, 0],
    ['PAN 13', 'Equipo Panama', 0, 0],
    ['PAN 14', 'Édgar Bárcenas', 0, 0],
    ['PAN 15', 'Carlos Harvey', 0, 0],
    ['PAN 16', 'Ismael Díaz', 0, 0],
    ['PAN 17', 'José Fajardo', 0, 0],
    ['PAN 18', 'Cecilo Waterman', 0, 0],
    ['PAN 19', 'José Luis Rodríguez', 0, 0],
    ['PAN 20', 'Alberto Quintero', 0, 0],
    // 🥤 SECCIÓN ESPECIAL COCA-COLA
    ['CC 1 ', 'Coca-Cola - Lamine Yamal', 1, 0],
    ['CC 2 ', 'Coca-Cola - Joshua Himmich', 1, 0],
    ['CC 3 ', 'Coca-Cola - Harry Kane', 1, 0],
    ['CC 4 ', 'Coca-Cola - Santiago Giménez', 1, 0],
    ['CC 5 ', 'Coca-Cola - Josko Gvardiol', 1, 0],
    ['CC 6 ', 'Coca-Cola - Federico Valverde', 1, 0],
    ['CC 7 ', 'Coca-Cola - Jefferson Lerma', 1, 0],
    ['CC 8 ', 'Coca-Cola - Enner Valencia', 1, 0],
    ['CC 9 ', 'Coca-Cola - Gabriel Magalhaes', 1, 0],
    ['CC 10 ', 'Coca-Cola - Virgil Van Dijk', 1, 0],
    ['CC 11 ', 'Coca-Cola - Alphonso Davies', 1, 0],
    ['CC 12 ', 'Coca-Cola - Emiliano Martínez', 1, 0],
    ['CC 13 ', 'Coca-Cola - Raúl Jiménez', 1, 0],
    ['CC 14 ', 'Coca-Cola - Lautaro Martínez', 1, 0],

];